### ISSUE TITLE
Build errors after importing binary plug-in project

### ISSUE THREAD

**Issue by pnehrer** [ecliptical/ds-annotations#25]
When a binary plug-in project is imported into the workspace, an error is reported each time the build runs:

java.lang.NullPointerException
	at org.eclipse.pde.internal.core.text.AbstractEditingModel.getInputStream(AbstractEditingModel.java:175)
	at org.eclipse.pde.internal.core.text.AbstractEditingModel.load(AbstractEditingModel.java:127)
	at org.eclipse.pde.internal.ui.util.PDEModelUtility.prepareAbstractEditingModel(PDEModelUtility.java:489)
	at org.eclipse.pde.internal.ui.util.PDEModelUtility.generateModelEdits(PDEModelUtility.java:331)
	at org.eclipse.pde.internal.ui.util.PDEModelUtility.modifyModel(PDEModelUtility.java:281)
	at ca.ecliptical.pde.internal.ds.DSAnnotationCompilationParticipant.updateProject(DSAnnotationCompilationParticipant.java:394)
	at ca.ecliptical.pde.internal.ds.DSAnnotationCompilationParticipant.buildFinished(DSAnnotationCompilationParticipant.java:360)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:233)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:733)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

**Comment by pnehrer** [comment]
FYI this is related to https://bugs.eclipse.org/bugs/show_bug.cgi?id=488440
